[project]
name = "lerobot-hdf5"
version = "0.1.0"
description = "Takes a HDF5 file and converts it to LeRobot v3.0."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dacite>=1.9.2",
    "h5py>=3.15.1",
    "lerobot>=0.4.3",
    "numpy>=2.4.2",
    "tyro>=1.0.6",
]
